# config/packages/security.yaml
security:
    # ⬇️ ELIMINA ESTA LÍNEA (obsoleta en Symfony 6+)
    # enable_authenticator_manager: true

    role_hierarchy:
        ROLE_ADMIN: [ROLE_MANAGER, ROLE_INVENTORY_MANAGER, ROLE_USER]
        ROLE_MANAGER: [ROLE_INVENTORY_MANAGER, ROLE_USER]
        ROLE_INVENTORY_MANAGER: [ROLE_USER]
        ROLE_USER: []

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto
            cost: 12

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        login:
            pattern: ^/api/auth/login
            stateless: true
            json_login:
                check_path: /api/auth/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~
            entry_point: jwt

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

    access_control:
        - { path: ^/api/auth/(login|register|health), roles: PUBLIC_ACCESS }
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/api/manager, roles: ROLE_MANAGER }
        - { path: ^/api/inventory, roles: ROLE_INVENTORY_MANAGER }
        - { path: ^/api, roles: ROLE_USER }
