controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

    # config/routes.yaml
    # Rutas de autenticación
api_auth_register:
    path: /api/auth/register
    controller: App\Controller\AuthController::register
    methods: POST

api_auth_health:
    path: /api/auth/health
    controller: App\Controller\AuthController::health
    methods: GET

# ELIMINA estas rutas duplicadas:
# app_home, app_login, app_logout, app_register, app_users, app_user_delete
# porque ya están definidas con atributos en los controladores
